"""Add category, user_id, household_id to services

Revision ID: c7ba0df944c4
Revises: 47fd3bf387ce
Create Date: 2025-09-26 10:26:18.618645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ba0df944c4'
down_revision = '47fd3bf387ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('household_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_services_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_services_household_id_households'), 'households', ['household_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_services_household_id_households'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_services_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('household_id')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
