"""empty message

Revision ID: e530f5126587
Revises: ae2a76735783
Create Date: 2025-09-26 16:57:01.119811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e530f5126587'
down_revision = 'ae2a76735783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reimbursed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_history', schema=None) as batch_op:
        batch_op.drop_column('reimbursed')
        batch_op.drop_column('paid_date')

    # ### end Alembic commands ###
